-- AlterEnum
ALTER TYPE "InAppNotificationType" ADD VALUE 'APPOINTMENT_CONFIRMED';
ALTER TYPE "InAppNotificationType" ADD VALUE 'APPOINTMENT_REJECTED';
ALTER TYPE "InAppNotificationType" ADD VALUE 'APPOINTMENT_CANCELLED_BY_BUSINESS';
