// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Env vars live in apps/web/.env (single source of truth for the whole
// workspace) rather than a duplicate packages/db/.env.
config({ path: "../../apps/web/.env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI-only (migrate/studio): prefer the non-pooled connection so
    // migrations don't run advisory locks/DDL through a transaction
    // pooler. The app's runtime client (packages/db/src/client.ts)
    // uses DATABASE_URL (pooled) independently of this file.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
